# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-06 14:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=555)),
                ('icon', models.FileField(blank=True, null=True, upload_to='icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationType',
            fields=[
                ('type_id', models.CharField(max_length=155, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('polygon_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shape', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=800, null=True)),
                ('level', models.IntegerField(choices=[(0, 'Root polygon'), (1, 'Regions of country'), (2, 'Subregions or big sities'), (3, 'Towns or districts of city'), (4, 'Houses')], default=4)),
                ('is_verified', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('layer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctracker.Polygon')),
                ('organizations', models.ManyToManyField(blank=True, to='ctracker.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_file', models.FileField(upload_to='geojsons')),
            ],
            options={
                'verbose_name_plural': 'Uploader',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctracker.OrganizationType'),
        ),
        migrations.AddField(
            model_name='claimtype',
            name='org_type',
            field=models.ManyToManyField(to='ctracker.OrganizationType'),
        ),
    ]
