# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-10 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_populate_local_and_reply_and_share_counts'),
        ('users', '0025_user_picture_ppoi'),
        ('ctracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.Content')),
                ('servant', models.CharField(max_length=550)),
                ('bribe', models.IntegerField(blank=True, null=True)),
                ('claim_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctracker.ClaimType')),
                ('complainer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctracker.Organization')),
            ],
            bases=('content.content',),
        ),
    ]
